#!/bin/bash

upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds} % 60))
mins=$((${upSeconds} / 60 % 60))
hours=$((${upSeconds} / 3600 % 24))
days=$((${upSeconds} / 86400))
UPTIME=$(printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs")

# get the load averages
read one five fifteen rest </proc/loadavg

echo "
Date..............: $(date +"%A, %e %B %Y, %r")
Uptime............: ${UPTIME}
Memory............: $(cat /proc/meminfo | grep MemFree | awk {'print $2'})kB (Free) / $(cat /proc/meminfo | grep MemTotal | awk {'print $2'})kB (Total)
Load Averages.....: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
Running Processes.: $(ps ax | wc -l | tr -d " ")
Core Temperature..: $(perl -e 'm/(\d+)/; $c=$1/1000; s/\d+//; $f = $c * 9 / 5 + 32; for ($f, $cputemp){ $_ = sprintf ( "%.1f" ,  $_  ) }; print "$c° C ($f° F)";' -p /sys/class/thermal/thermal_zone0/temp)
IP Addresses......: $(ip a | grep glo | awk '{print $2}' | head -1 | cut -f1 -d/) and $(wget -q -O - http://icanhazip.com/ | tail)
"
echo "AWS: " 
aws --version
echo "python: "
python --version
echo "node: "
node -v