# files: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-files.html
# permissions: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-permissions.html
# hooks: https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-server
version: 0.0
os: linux
files:
  - source: /
    destination: /etc/update-motd.d/
    overwrite: true
permissions:
  - object: /etc/update-motd.d
    owner: pi
    group: adm
    mode: 740
    type:
      - directory
  - object: /etc/update-motd.d/
    pattern: '*'
    owner: pi
    group: adm
    mode: 740
    type:
      - file
# hooks:
#   BeforeInstall:
#     - location: /home/pi/sh/setup.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/change_permissions.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/start_server.sh
#     - location: scripts/create_test_db.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server.sh
#       timeout: 300
#       runas: root
